require: rubocop-rails

AllCops:
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    -
Rails/SkipsModelValidations:
  Exclude:
    - 'lib/providers/*.rb'
Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/*.rb'
Metrics/MethodLength:
  Max: 20